# This is a basic workflow to help you get started with Actions

name: "Update Certs"

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  workflow_dispatch:
    inputs:
      AUTOCERT_FORCE_PUSH:
        description: 'Force do git push'
        required: true
        default: 'false'
        type: choice
        options:
        - 'false'
        - 'true'
      AUTOCERT_FORCE_REISSUE:
        description: 'Force remove old cert and reissue new cert'
        required: true
        default: 'false'
        type: choice
        options:
        - 'false'
        - 'true'
  schedule:
    - cron: '0 20 1 * *'

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
    - uses: actions/checkout@v2

    # Runs a set of commands using the runners shell
    - name: Run AutoCert CI Cron
      env: 
        AUTOCERT_FORCE_PUSH: ${{ inputs.AUTOCERT_FORCE_PUSH }}
        CERT_GIT_EMAIL: ci@kenvix.com
        CERT_GIT_USER: Kenvix-AutoCert-CI
        CERT_GIT_BRANCH: master
        CERT_GIT_URI: git@github.com:kenvix/cert.git
        CERT_GIT_COMMIT_MESSAGE: AutoCert Update
      run: |
        pushd $GITHUB_WORKSPACE
        chmod +x ci-cron.sh
        ./ci-cron.sh
        popd
#     - name: Upload Certs as artifact
#       uses: actions/upload-artifact@v1
#       with:
#         name: Certs
#         path: data/acme
